name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Lint Check
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install cppcheck-codequality
        
    - name: Run CPPCheck
      run: |
        # 安装cppcheck
        sudo apt-get update
        sudo apt-get install -y cppcheck
        
        # 检查C源文件
        find SC95F8523_8522_8521_8520S_8520M_Demo_Code/c -name "*.c" -exec cppcheck --enable=all --std=c89 --platform=unix32 {} \;
        
    - name: Check file encoding
      run: |
        # 检查文件编码是否为UTF-8或ASCII
        find . -name "*.c" -o -name "*.h" -o -name "*.H" | xargs file --mime-encoding
        
    - name: Check line endings
      run: |
        # 检查行尾格式
        find . -name "*.c" -o -name "*.h" -o -name "*.H" -o -name "*.md" | xargs file

  documentation:
    runs-on: ubuntu-latest
    name: Documentation Check
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Check README
      run: |
        if [ ! -f README.md ]; then
          echo "README.md not found!"
          exit 1
        fi
        
    - name: Check CHANGELOG
      run: |
        if [ ! -f CHANGELOG.md ]; then
          echo "CHANGELOG.md not found!"
          exit 1
        fi
        
    - name: Check LICENSE
      run: |
        if [ ! -f LICENSE ]; then
          echo "LICENSE file not found!"
          exit 1
        fi

  structure:
    runs-on: ubuntu-latest
    name: Project Structure Check
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Check project structure
      run: |
        # 检查必要的目录结构
        if [ ! -d "SC95F8523_8522_8521_8520S_8520M_Demo_Code" ]; then
          echo "Main code directory not found!"
          exit 1
        fi
        
        if [ ! -d "SC95F8523_8522_8521_8520S_8520M_Demo_Code/c" ]; then
          echo "Source code directory not found!"
          exit 1
        fi
        
        if [ ! -d "SC95F8523_8522_8521_8520S_8520M_Demo_Code/H" ]; then
          echo "Header files directory not found!"
          exit 1
        fi
        
        if [ ! -f "SC95F8523_8522_8521_8520S_8520M_Demo_Code/c/main.c" ]; then
          echo "main.c not found!"
          exit 1
        fi
        
    - name: Check for sensitive files
      run: |
        # 检查是否有敏感文件被提交
        if find . -name "*.uvgui.*" -o -name "*.bak" -o -name "*.tmp" | grep -q .; then
          echo "Sensitive or temporary files found in repository!"
          find . -name "*.uvgui.*" -o -name "*.bak" -o -name "*.tmp"
          exit 1
        fi
